/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as MyRouteImport } from './routes/my'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SportsIdRouteImport } from './routes/sports.$id'
import { Route as MySubmissionsRouteImport } from './routes/my.submissions'
import { Route as MyFavoritesRouteImport } from './routes/my.favorites'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminSportsRouteImport } from './routes/admin.sports'
import { Route as AdminPickupRouteImport } from './routes/admin.pickup'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SportsIdRoute = SportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SportsRoute,
} as any)
const MySubmissionsRoute = MySubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => MyRoute,
} as any)
const MyFavoritesRoute = MyFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => MyRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSportsRoute = AdminSportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPickupRoute = AdminPickupRouteImport.update({
  id: '/pickup',
  path: '/pickup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRouteWithChildren
  '/ranking': typeof RankingRoute
  '/sports': typeof SportsRouteWithChildren
  '/submit': typeof SubmitRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/pickup': typeof AdminPickupRoute
  '/admin/sports': typeof AdminSportsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/my/favorites': typeof MyFavoritesRoute
  '/my/submissions': typeof MySubmissionsRoute
  '/sports/$id': typeof SportsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRouteWithChildren
  '/ranking': typeof RankingRoute
  '/sports': typeof SportsRouteWithChildren
  '/submit': typeof SubmitRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/pickup': typeof AdminPickupRoute
  '/admin/sports': typeof AdminSportsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/my/favorites': typeof MyFavoritesRoute
  '/my/submissions': typeof MySubmissionsRoute
  '/sports/$id': typeof SportsIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRouteWithChildren
  '/ranking': typeof RankingRoute
  '/sports': typeof SportsRouteWithChildren
  '/submit': typeof SubmitRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/pickup': typeof AdminPickupRoute
  '/admin/sports': typeof AdminSportsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/my/favorites': typeof MyFavoritesRoute
  '/my/submissions': typeof MySubmissionsRoute
  '/sports/$id': typeof SportsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/categories'
    | '/dashboard'
    | '/login'
    | '/my'
    | '/ranking'
    | '/sports'
    | '/submit'
    | '/admin/categories'
    | '/admin/pickup'
    | '/admin/sports'
    | '/admin/submissions'
    | '/my/favorites'
    | '/my/submissions'
    | '/sports/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/login'
    | '/my'
    | '/ranking'
    | '/sports'
    | '/submit'
    | '/admin/categories'
    | '/admin/pickup'
    | '/admin/sports'
    | '/admin/submissions'
    | '/my/favorites'
    | '/my/submissions'
    | '/sports/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/categories'
    | '/dashboard'
    | '/login'
    | '/my'
    | '/ranking'
    | '/sports'
    | '/submit'
    | '/admin/categories'
    | '/admin/pickup'
    | '/admin/sports'
    | '/admin/submissions'
    | '/my/favorites'
    | '/my/submissions'
    | '/sports/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyRoute: typeof MyRouteWithChildren
  RankingRoute: typeof RankingRoute
  SportsRoute: typeof SportsRouteWithChildren
  SubmitRoute: typeof SubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sports/$id': {
      id: '/sports/$id'
      path: '/$id'
      fullPath: '/sports/$id'
      preLoaderRoute: typeof SportsIdRouteImport
      parentRoute: typeof SportsRoute
    }
    '/my/submissions': {
      id: '/my/submissions'
      path: '/submissions'
      fullPath: '/my/submissions'
      preLoaderRoute: typeof MySubmissionsRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/favorites': {
      id: '/my/favorites'
      path: '/favorites'
      fullPath: '/my/favorites'
      preLoaderRoute: typeof MyFavoritesRouteImport
      parentRoute: typeof MyRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sports': {
      id: '/admin/sports'
      path: '/sports'
      fullPath: '/admin/sports'
      preLoaderRoute: typeof AdminSportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pickup': {
      id: '/admin/pickup'
      path: '/pickup'
      fullPath: '/admin/pickup'
      preLoaderRoute: typeof AdminPickupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminPickupRoute: typeof AdminPickupRoute
  AdminSportsRoute: typeof AdminSportsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminPickupRoute: AdminPickupRoute,
  AdminSportsRoute: AdminSportsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MyRouteChildren {
  MyFavoritesRoute: typeof MyFavoritesRoute
  MySubmissionsRoute: typeof MySubmissionsRoute
}

const MyRouteChildren: MyRouteChildren = {
  MyFavoritesRoute: MyFavoritesRoute,
  MySubmissionsRoute: MySubmissionsRoute,
}

const MyRouteWithChildren = MyRoute._addFileChildren(MyRouteChildren)

interface SportsRouteChildren {
  SportsIdRoute: typeof SportsIdRoute
}

const SportsRouteChildren: SportsRouteChildren = {
  SportsIdRoute: SportsIdRoute,
}

const SportsRouteWithChildren =
  SportsRoute._addFileChildren(SportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyRoute: MyRouteWithChildren,
  RankingRoute: RankingRoute,
  SportsRoute: SportsRouteWithChildren,
  SubmitRoute: SubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
